spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        #          filters:
        #            - AuthFilter
        - id: JOURNEY-SERVICE
          uri: lb://JOURNEY-SERVICE
          predicates:
            - Path=/api/v1/journeys/**
          filters:
            - AuthFilter

        - id: CAR-SERVICE
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/api/v1/cars/**
          filters:
            - AuthFilter

        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthFilter

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka