spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
#          filters:
#            - AuthFilter

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka